In [1]:
import torch

In [2]:
A = torch.randn(3, 3) # normal
B = torch.rand(3, 3) # uniform
print(A)
print(B)

tensor([[-2.0731,  0.3814, -0.1032],
        [ 0.1355, -2.2536,  0.0864],
        [ 0.5037,  1.6574, -0.0855]])
tensor([[0.9006, 0.9321, 0.6352],
        [0.1437, 0.5187, 0.7548],
        [0.7851, 0.8739, 0.2287]])


In [8]:
A = torch.randn(3, 3)

print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))

print(torch.log(torch.exp(torch.tensor(1))))
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))

print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[-0.1457,  1.1508,  0.7210],
        [-0.2493, -0.7055,  2.3944],
        [-0.2575, -1.1625,  0.4843]])
tensor([[0.1457, 1.1508, 0.7210],
        [0.2493, 0.7055, 2.3944],
        [0.2575, 1.1625, 0.4843]])
tensor([[0.3817, 1.0727, 0.8491],
        [0.4993, 0.8399, 1.5474],
        [0.5075, 1.0782, 0.6959]])
tensor([[ 0.8644,  3.1606,  2.0564],
        [ 0.7793,  0.4939, 10.9617],
        [ 0.7730,  0.3127,  1.6230]])
tensor([[-1.9264,  0.1404, -0.3272],
        [-1.3890, -0.3489,  0.8731],
        [-1.3566,  0.1506, -0.7251]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[-0.,  1.,  1.],
        [-0., -1.,  2.],
        [-0., -1.,  0.]])
tensor([[-0.1500,  1.1500,  0.7200],
        [-0.2500, -0.7100,  2.3900],
        [-0.2600, -1.1600,  0.4800]])
tensor([[-1.,  1.,  0.],
        [-1., -1.,  2.],
        [-1., -2.,  0.]])
tensor([[-0.,  2.,  1.],
        [-0., -0.,  3.],
        [-0., -1.,  1.]])


In [11]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1) / 6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [13]:
torch.nan
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1, 2, torch.nan, 3, 4])))
print(torch.isinf(torch.tensor([1, 2, 3, 4, torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [16]:
A = torch.randn(3, 4)
print(A)

print(torch.max(A))
print(torch.max(A, dim=0))
print(torch.max(A, dim=1))

tensor([[ 0.0089, -0.2562, -0.3923, -1.1896],
        [ 1.5892,  0.3007,  1.2254, -0.9372],
        [ 0.3417, -0.1806, -0.5549,  0.6805]])
tensor(1.5892)
torch.return_types.max(
values=tensor([1.5892, 0.3007, 1.2254, 0.6805]),
indices=tensor([1, 1, 1, 2]))
torch.return_types.max(
values=tensor([0.0089, 1.5892, 0.6805]),
indices=tensor([0, 0, 3]))


In [17]:
print(torch.max(A, dim=0, keepdims=True))
print(torch.max(A, dim=1, keepdims=True))

torch.return_types.max(
values=tensor([[1.5892, 0.3007, 1.2254, 0.6805]]),
indices=tensor([[1, 1, 1, 2]]))
torch.return_types.max(
values=tensor([[0.0089],
        [1.5892],
        [0.6805]]),
indices=tensor([[0],
        [0],
        [3]]))


In [18]:
print(torch.min(A))
print(torch.min(A, dim=0))
print(torch.min(A, dim=1))

tensor(-1.1896)
torch.return_types.min(
values=tensor([ 0.0089, -0.2562, -0.5549, -1.1896]),
indices=tensor([0, 0, 2, 0]))
torch.return_types.min(
values=tensor([-1.1896, -0.9372, -0.5549]),
indices=tensor([3, 3, 2]))


In [23]:
print(torch.argmax(A))
print(torch.argmax(A, dim=0))
print(torch.argmax(A, dim=1))

tensor(4)
tensor([1, 1, 1, 2])
tensor([0, 0, 3])


In [28]:
a = torch.randn(6, 1)
print(a)

a_sorted = torch.sort(a, dim=0)
print(a_sorted)

a = torch.randn(6, 1)
print(a)
print(a.sort(dim=0))
print(a.sort(dim=0, descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())


tensor([[-0.0416],
        [-0.8556],
        [ 0.0664],
        [ 0.0192],
        [-0.3736],
        [-0.4707]])
torch.return_types.sort(
values=tensor([[-0.8556],
        [-0.4707],
        [-0.3736],
        [-0.0416],
        [ 0.0192],
        [ 0.0664]]),
indices=tensor([[1],
        [5],
        [4],
        [0],
        [3],
        [2]]))
tensor([[-0.9320],
        [ 1.0381],
        [ 1.5541],
        [ 2.3472],
        [ 0.3879],
        [-0.8890]])
torch.return_types.sort(
values=tensor([[-0.9320],
        [-0.8890],
        [ 0.3879],
        [ 1.0381],
        [ 1.5541],
        [ 2.3472]]),
indices=tensor([[0],
        [5],
        [4],
        [1],
        [2],
        [3]]))
torch.return_types.sort(
values=tensor([[ 2.3472],
        [ 1.5541],
        [ 1.0381],
        [ 0.3879],
        [-0.8890],
        [-0.9320]]),
indices=tensor([[3],
        [2],
        [1],
        [4],
        [5],
        [0]]))
tensor(2.3472)
tensor(2.3472)
tensor([[0.9320],
        [1.038

In [39]:
A = torch.randn(3, 4)
print(A)
print(torch.sum(A))
print(torch.sum(A, dim=1))
print(torch.sum(A, dim=1, keepdim=True))

print(torch.mean(A))
print(torch.mean(A, dim=1))
print(torch.mean(A, dim=1, keepdim= True))
print(torch.std(A)) # 표준편차

print(A.sum(dim=1, keepdim=True))
print(A.mean(dim=1, keepdim=True))
print(A.std())

tensor([[-1.3786, -1.3433, -0.4357,  0.4955],
        [-0.1923,  0.2531,  0.7716,  1.7113],
        [ 0.9896, -0.7918, -0.9380,  0.5714]])
tensor(-0.2874)
tensor([-2.6621,  2.5437, -0.1689])
tensor([[-2.6621],
        [ 2.5437],
        [-0.1689]])
tensor(-0.0239)
tensor([-0.6655,  0.6359, -0.0422])
tensor([[-0.6655],
        [ 0.6359],
        [-0.0422]])
tensor(0.9803)
tensor([[-2.6621],
        [ 2.5437],
        [-0.1689]])
tensor([[-0.6655],
        [ 0.6359],
        [-0.0422]])
tensor(0.9803)


In [43]:
A = torch.randint(1, 5, size=(12,))
print(A)
print(A.shape)

B = A.reshape(2, 2, 3)
print(B)
print(B.ndim)

tensor([1, 4, 4, 1, 4, 3, 3, 4, 2, 2, 4, 2])
torch.Size([12])
tensor([[[1, 4, 4],
         [1, 4, 3]],

        [[3, 4, 2],
         [2, 4, 2]]])
3


In [52]:
A = torch.arange(20,)
print(A)
print(A.reshape(4, 5))
print(A.reshape(4, -1).shape)
print(A.reshape(2, 5, -1).shape)
print(A.reshape(2, -1, 5).shape)
print(A.reshape(1, -1).shape) # 2차원 행 벡터
print(A.reshape(-1, 1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 1])
print(torch.sum(a * b))

a = a.reshape(3, 1)
b = b.reshape(3, 1)
print(a.transpose(1, 0) @ b)
print(a.permute(1, 0)@b)
print(a.T@b)
print(a.t()@b)

A = torch.randn(4, 3, 6)
print(A.permute(1, 2, 0).shape)
print(A.transpose(1, 2).shape)

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([3, 6, 4])
torch.Size([4, 6, 3])


In [72]:
x = torch.randn(2, 3, 4, 5, 6)
print(x[1, 2,:, :, :].shape)
print(x[1, 2,...].shape)
print(x[:,:,:,:,3])
print(x[...,3].shape)
print(x[1, :, :, 3, :].shape)
print(x[1, ...,3,:].shape)

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
tensor([[[[-0.9682,  0.4120,  0.3709,  0.4564, -1.2574],
          [-1.6235, -0.8163, -0.8044,  0.3685,  1.0952],
          [-0.9350,  0.6411,  0.5927, -0.5144, -0.0231],
          [-0.3909, -1.2895,  0.1950, -1.3824, -1.8653]],

         [[ 1.8856,  0.3664,  0.4145,  0.5331, -0.5455],
          [-1.4024,  0.3732,  1.1536,  0.8306, -2.3262],
          [ 1.7669, -0.0144,  0.0272, -0.8478,  1.2756],
          [ 0.6431,  1.6706, -1.6543, -1.4262, -0.9112]],

         [[-0.2127, -1.1942,  2.3389, -0.7540, -0.3655],
          [ 1.1844,  1.6505,  1.4915, -0.5695,  2.8064],
          [-1.2232,  1.3357,  0.7502, -1.9773,  0.1636],
          [ 0.9495,  1.1659, -1.8513, -1.2656,  0.1380]]],


        [[[ 0.5067, -0.7932,  1.9580, -0.7146,  0.2881],
          [ 0.5589, -0.2420, -0.5494,  0.9025, -0.6907],
          [ 0.2228,  1.4324,  1.4182, -0.4558, -0.2870],
          [ 1.5671,  0.1724,  1.7708, -1.4409,  0.0828]],

         [[-0.6172, -1.7653,  1.23

In [78]:
A = torch.ones(3, 4)
B = torch.zeros(3, 4)
C = torch.vstack([A, B])
D = torch.hstack([A, B]) # v는 0번째 차원, h는 1번째 차원
E = torch.cat([A, B], dim=0)
F = torch.cat([A, B], dim=1)

print(C)
print(D)
print(E)
print(F)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])


In [85]:
A = torch.randn(1,1,1,3,1,1,1,4,1,1,1)

print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(dim=(0, 2, 4, 5)).shape)

torch.Size([1, 1, 1, 3, 1, 1, 1, 4, 1, 1, 1])
torch.Size([3, 4])
torch.Size([1, 3, 1, 4, 1, 1, 1])


In [88]:
A = torch.randn(3, 4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [89]:
A = torch.ones(3, 4)
B = torch.zeros(3, 4)
A = A.unsqueeze(dim = 0)
B = B.unsqueeze(dim = 0)
C = torch.cat([A, B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [ ]:
A = torch.ones(3,4)
B = torch.zeros(3,4)
C = torch.stack([A, B])  # 차원을 추가해서 쌓음, * shape이 완전히 일치해야함
print(C)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [92]:
A = torch.tensor([[1, 2], [3, 4]])
# B = A # 주소까지 복사
B = A.clone()
B[0, 0] = 100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


In [93]:
A = torch.randn(5, 7)
B = torch.randn(7, 10)
C = A @ B
print(C.shape)

A = torch.randn(32, 5, 7)
B = torch.randn(32, 7, 10)
C =  A @ B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [94]:
A = torch.randn(32, 5, 7)
B = torch.randn(7, 10)

C = A @ B
print(C.shape)

torch.Size([32, 5, 10])


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = torch.tensor([1, 2, 3])
A = torch.tensor(a) # A = torch.from_numpy(a)
B = b.numpy() # B = np.array(b)
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
