In [1]:
import torch
from torch import nn

In [4]:
x = torch.randn(100, 3)
layer = nn.Linear(3, 5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 0.3150, -0.2232,  0.5345],
        [-0.3237,  0.3685, -0.5350],
        [-0.3902, -0.1272,  0.5151],
        [-0.5226,  0.3688,  0.5218],
        [ 0.4779, -0.0953,  0.2341]], requires_grad=True)
Parameter containing:
tensor([-0.2664, -0.3011, -0.0301, -0.0487, -0.4731], requires_grad=True)


In [3]:
x = torch.randn(2, 5)
layer = nn.ReLU()
print(x)
print(layer(x))

tensor([[-0.8082, -0.2017, -0.6551,  0.2314,  1.8757],
        [-0.3663, -0.2602, -1.1768,  0.4068, -0.1238]])
tensor([[0.0000, 0.0000, 0.0000, 0.2314, 1.8757],
        [0.0000, 0.0000, 0.0000, 0.4068, 0.0000]])


In [18]:
layer = nn.BatchNorm1d(3)
print(layer.weight) # 스케일 파라미터
print(layer.bias) # 시프트 파라미터

x = torch.randn(5, 3)
print(x)
print(layer(x))

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([[ 0.4116,  0.6622, -1.5994],
        [ 0.0056, -0.3180, -1.0906],
        [-0.2844, -0.5841, -0.5170],
        [ 0.1706,  2.8495,  2.1582],
        [-0.7289,  0.5421,  1.2948]])
tensor([[ 1.2620,  0.0264, -1.1466],
        [ 0.2304, -0.7844, -0.7927],
        [-0.5065, -1.0045, -0.3938],
        [ 0.6498,  1.8356,  1.4668],
        [-1.6357, -0.0730,  0.8663]], grad_fn=<NativeBatchNormBackward0>)


In [19]:
layer = nn.LayerNorm(3)
print(layer.weight) # 스케일 파라미터
print(layer.bias) # 시프트 파라미터

x = torch.randn(5, 3)
print(x)
print(layer(x))

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([[ 1.2153, -1.5890,  1.3385],
        [-0.5538,  0.0478, -0.6904],
        [ 0.1404,  1.3030,  0.4088],
        [-0.3741,  0.8841, -2.9325],
        [ 0.2205,  0.1330,  1.4159]])
tensor([[ 0.6611, -1.4132,  0.7522],
        [-0.4834,  1.3926, -0.9092],
        [-0.9597,  1.3794, -0.4197],
        [ 0.2729,  1.0653, -1.3382],
        [-0.6311, -0.7805,  1.4116]], grad_fn=<NativeLayerNormBackward0>)


In [25]:
layer = nn.BatchNorm2d(3)
print(layer.weight)
print(layer.bias)
x = torch.randn(5, 3, 32, 32)
print(layer(x).shape)

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
torch.Size([5, 3, 32, 32])


In [34]:
x = torch.randn(3, 7)
drop = nn.Dropout(p = 0.1) # 구현에서 p는 죽일 확률
print(x)
print(drop(x) * (1 - 0.1))
drop.eval()
print(drop(x))

tensor([[-0.3845, -0.5713,  1.6759,  1.4061,  0.6585, -1.1067,  1.6656],
        [ 0.5114, -1.0285, -0.6001,  1.1389, -0.3832,  1.2290,  0.1345],
        [ 0.3324, -0.3695, -1.5874, -0.7940, -0.4696,  0.4641,  0.1636]])
tensor([[-0.3845, -0.5713,  1.6759,  0.0000,  0.6585, -1.1067,  1.6656],
        [ 0.0000, -1.0285, -0.6001,  1.1389, -0.3832,  1.2290,  0.1345],
        [ 0.3324, -0.3695, -1.5874, -0.7940, -0.4696,  0.4641,  0.1636]])
tensor([[-0.3845, -0.5713,  1.6759,  1.4061,  0.6585, -1.1067,  1.6656],
        [ 0.5114, -1.0285, -0.6001,  1.1389, -0.3832,  1.2290,  0.1345],
        [ 0.3324, -0.3695, -1.5874, -0.7940, -0.4696,  0.4641,  0.1636]])


In [36]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer = nn.Sequential(nn.Linear(5, 7),
                                        nn.ReLU(),
                                        nn.Dropout(p=0.3))
    
    def forward(self, x):
        x = self.drop_layer(x)
        return x

model = sample_model()
model.train()
x = torch.randn(3, 5)
print(model(x))

model.eval()
print(model(x))

tensor([[1.7471, 0.0000, 1.0473, 0.0000, 0.0000, 0.3230, 0.0000],
        [0.3837, 0.0000, 0.0000, 0.0000, 1.5146, 0.0000, 0.0000],
        [0.0000, 1.1444, 0.0000, 1.1557, 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)
tensor([[1.2230, 0.0000, 0.7331, 0.0000, 0.5645, 0.2261, 0.0000],
        [0.2686, 0.0000, 0.2582, 0.1962, 1.0602, 1.4235, 0.0000],
        [0.0000, 0.8011, 0.0000, 0.8090, 0.3599, 0.0000, 0.0000]],
       grad_fn=<ReluBackward0>)
